### ISSUE TITLE
Figure captions

### ISSUE THREAD

**Issue by mvuorre** [rstudio/radix#10]
Thanks for the great publication format!

Currently, figures created in an R code chunk do not get a figure number in the caption, nor is the caption text formatted (unlike when an alternative text is provided in e.g. `![Figure from https://example.com](heatmap.png)`). Would it be possible to 1. output figure numbers into figure captions, and 2. format figure captions similar to how captions to `![Figure from https://example.com](heatmap.png)` images are formatted?

**Comment by jjallaire** [comment]
I just modified the CSS for figure captions output by knitr chunks to have the same appearance as external figures (as you referenced/requested): https://github.com/radixpub/radix-r/commit/89523e1a5fb0a290b1685af6ae870d9c993c43b9

In terms of numbering figures, I think this is still an issue w/ pandoc: https://github.com/jgm/pandoc/issues/813

@yihui I'm assuming this would be resolved if I could call your cross-reference code from bookdown as we discussed last week. Is this function callable yet?
