### ISSUE TITLE
Hyperlinks in footnotes

### ISSUE THREAD

**Issue by dakvid** [rstudio/radix#15]
Really excited about this package, thanks!
It seems that hyperlinks get stripped from footnotes, which I haven't seen in other RMarkdown formats. These can be handy at times, so is it possible to have them supported?

`Download the latest [RStudio](https://www.rstudio.com/products/rstudio/download/)^[Or try the [preview download](https://www.rstudio.com/products/rstudio/download/preview/)]`

`Download the latest RStudio^[https://www.rstudio.com/products/rstudio/download/preview/]`

**Comment by jjallaire** [comment]
Thanks for reporting this, fixed here: https://github.com/rstudio/radix/commit/f7ee17bffa22daa8cdf3560248aca76aecb3d971
