### ISSUE TITLE
SQL code blocks disappear

### ISSUE THREAD

**Issue by dakvid** [rstudio/radix#17]
If I put a code block with SQL:
````
```sql
SELECT *
FROM my_table
```
````
the contents disappear from the output. (A code block is there, but there's nothing in it.)

It doesn't appear to be SQL specific. There appears to be a list of languages that work (including r, c, cpp, java, python, julia, javascript, css) but anything else (sql, rust, haskell, d, brainfuck, ...) disappears.

**Comment by epspi** [comment]
A little more detail: 
The `pre` element within the `d-code block` tag is missing for the sql chunk but present for the chunks that render correctly. A child of `pre` that's supposed to contain the code (`code id="code-container"`) is actually there there but
1.  it has nothing in it and
2.  it doesn't carry a language class  

![image](https://user-images.githubusercontent.com/8306014/45884960-3279ab00-bd83-11e8-8864-827971a3fc86.png)


#### Results for R
```html
<pre>
    <code id="code-container" class="language-clike">
        data <span class="token operator">&lt;</span>
        <span class="token operator">-</span> iris
    </code>
</pre>
```

#### Results for Sql
```html
<code id="code-container"></code>
```

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/radix/commit/868669fc0c8d4776118a2ac83c37b93f8e7d5039

Our only option here was to map languages not supported directly by Prism to "clike"

**Comment by dakvid** [comment]
I'm a little confused, apologies if I'm misunderstanding something at some point. :-)

Prism.js supports 152 languages, including R and SQL: https://prismjs.com/#languages-list

However, looking at the source of [template/src/components/d-code.js](https://github.com/distillpub/template/blob/b854bd0124911e1be4744e472b67832e3251b96c/src/components/d-code.js) from distill, they only explicitly import python, clike, lua, bash, go, markdown and julia. So this could be fixed "properly" by importing more languages - but is this something that radix could override, or would it need a pull request to distill?

**Comment by jjallaire** [comment]
We'd have to remove the embedded Prism from Distill then replace it with another implementation. So far we've taken the approach not to fork/edit Distill but it may be that we'll ultimately need to.

**Comment by jjallaire** [comment]
Going to close this and create a new issue covering adding more Prism languages.
