### ISSUE TITLE
Error: Radix articles cannot be previewed in this version of RStudio.

### ISSUE THREAD

**Issue by slfan2013** [rstudio/radix#18]
> Please update to version 1.2.718 or higher at https://www.rstudio.com/products/rstudio/download/preview/

My version RStudio is "Version 1.2.1004", but I still got this error.

I think the error is because of the code
 `if (rstudio$version < "1.2.718")`

Truly, the `"1.2.1004"< "1.2.718"` is `TRUE`, which shouldn't be.

**Comment by jjallaire** [comment]
So if you execute the following from the console do you get the error:

```r
radix:::validate_rstudio_version()
```

Then, what is the output of `rstudioapi::versionInfo()$version` ?

**Comment by slfan2013** [comment]
Hi, the `radix:::validate_rstudio_version()` does not give any error.

`rstudioapi::versionInfo()$version` output is `‘1.2.1004’`

**Comment by hushuli** [comment]
> > Please update to version 1.2.718 or higher at https://www.rstudio.com/products/rstudio/download/preview/
> 
> My version RStudio is "Version 1.2.1004", but I still got this error.
> 
> I think the error is because of the code
> `if (rstudio$version < "1.2.718")`
> 
> Truly, the `"1.2.1004"< "1.2.718"` is `TRUE`, which shouldn't be.



> So if you execute the following from the console do you get the error:
> 
> ```r
> radix:::validate_rstudio_version()
> ```
> 
> Then, what is the output of `rstudioapi::versionInfo()$version` ?

I got the same error.

**Comment by yutannihilation** [comment]
> Truly, the `"1.2.1004"< "1.2.718"` is `TRUE`, which shouldn't be.

I think we should use `package_version()`.

``` r
"1.2.1004" < "1.2.718"
#> [1] TRUE
package_version("1.2.1004") < package_version("1.2.718")
#> [1] FALSE
```

<sup>Created on 2018-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by randomgambit** [comment]
same error for me fellas

**Comment by jjallaire** [comment]
Now I see, the rollover of the RStudio Preview version to 4 digits ("1004") is what is making this fail. Fix is checked in here: https://github.com/rstudio/radix/commit/1f08ddaf0e3f0a50c30599fc4b51c33c51596b86

To install the fixed version:

```r
devtools::install_github("rstudio/radix")
```

**Comment by randomgambit** [comment]
@jjallaire haha not so fast!
```

> devtools::install_github("rstudio/radix")
Downloading GitHub repo rstudio/radix@master
from URL https://api.github.com/repos/rstudio/radix/zipball/master
Installation failed: cannot open file 'C:/Users/john/AppData/Local/Temp/RtmpOcnWHZ/devtools6348504b600a/rstudio-radix-c3dba83/examples/websites/reproducible-finance-with-r/_posts/2017-03-07-quandl-and-forecasting/quandl-and-forecasting_files/dygraphs-binding-1.1.1.4/lib/dygraphs/dygraph-combined-dev.js': No such file or directory
```

**Comment by yutannihilation** [comment]
Curious. I see the same error on my Windows. 

> `cannot open file 'C:/Users/john/AppData/Local/Temp/RtmpOcnWHZ/devtools6348504b600a/rstudio-radix-c3dba83/examples/websites/reproducible-finance-with-r/_posts/2017-03-07-quandl-and-forecasting/quandl-and-forecasting_files/dygraphs-binding-1.1.1.4/lib/dygraphs/dygraph-combined-dev.js': No such file or directory`

This seems an error in `utils::unzip()`. Maybe there's a limit of path length? (Only on Windows...?)
I don't think radix is responsible for fixing this, but I guess considerable numbers of people will face this. Wish there's a nice workaround for this...

**Comment by yutannihilation** [comment]
I guess https://github.com/r-lib/remotes/issues/84 is (though this seems mistakenly closed...)

Anyway, this issue is definitely fixed. We should file a new issue if we want to continue the discussion.

**Comment by jjallaire** [comment]
Okay, I just removed that example site from the main repository (it was indeed an issue with path lengths and unzip)

**Comment by yutannihilation** [comment]
Thanks @jjallaire, I confirmed I can install the current master!

**Comment by geneorama** [comment]
Seems like it would be nice to update the [blog post](https://blog.rstudio.com/2018/09/19/radix-for-r-markdown/), and [tutorial](https://rstudio.github.io/radix/blog.html) to say that you need a preview version of RStudio and to install radix from github. 

I came here from the newsletter a few days ago, which I finally got around to trying.

**Comment by jjallaire** [comment]
Yes, both have been updated

**Comment by davidRCF** [comment]
Hi,

i try to work with radix package, i get this error:

> `Error: Radix requires RStudio v1.2 or greater. Please update at: https://www.rstudio.com/rstudio/download/preview/`

when i try to install new versioon of rstudio,i can not.

any idea?
thx
David

**Comment by jjallaire** [comment]
You need to provide more details than "when i try to install new versioon of rstudio,i can not". 

We have thousands of people successfully install every day so there is not a general problem with installation. We need to know specifically what is going wrong during installation. Failures to install RStudio are also better reported at https://github.com/rstudio/rstudio/issues

**Comment by dsaada** [comment]
I'm sorry, it's error was on my side. Radix work fine now.
many thanks
David

**Comment by aslm123** [comment]
This worked for me https://github.com/r-lib/remotes/issues/84#issuecomment-423752686. It opens a download list to choose and if you already have digest installed then you will want to skip that in the option to download. Afterwards Radix worked on my computer. This was the only suggestion that worked on my computer
