### ISSUE TITLE
Listing posts on other pages (not index.Rmd)

### ISSUE THREAD

**Issue by annafergusson** [rstudio/radix#22]
I get the following error message when I use the metadata entry (see https://rstudio.github.io/radix/blog.html#listing-pages) to list blog posts on pages that are not index.Rmd. 

_Error: The collection 'posts' does not have an article listing. (try running render_site() to generate the listing)_

Weirdly, as long as I use index.Rmd as a listing page, I can use other pages to list posts, but not another page by itself.

**Comment by jjallaire** [comment]
I'm not seeing that error in a simple site that I have locally. Could you provide the full source code of a site which exhibits this error? (or a link to a git repo that does)

**Comment by annafergusson** [comment]
Here's a link to a repo I just created using the default settings for a radix blog: https://github.com/annafergusson/radix-check/. I can't knit about.Rmd to make it the listings page without getting the error above.

**Comment by jjallaire** [comment]
The issue is that you are missing this line in the YAML for `index.Rmd`:

```yaml
site: radix::radix_website
```
If you used the RStudio template or `radix::create_blog()` function to create the site then this should have been added automatically, not sure why it's absent.

**Comment by annafergusson** [comment]
Why is it absent? :-) Because this human didn't read https://rstudio.github.io/radix/blog.html#listing-pages properly! Thanks @jjallaire

**Comment by jjallaire** [comment]
You bet, glad it's all working now :-)
