### ISSUE TITLE
error with the date in YAML

### ISSUE THREAD

**Issue by fderyckel** [rstudio/radix#23]
When I put this into the YAML it throws an error
date: "`r format(Sys.Date(), '%d %B, %Y')`"

Quitting from lines 2-9 () 
Error in parse(text = code, keep.source = FALSE) : 
  <text>:1:29: unexpected input
1: format(Sys.Date(), ''%d %B, %Y'')
                                ^
Calls: <Anonymous> ... hook_eval -> withVisible -> eval -> parse_only -> parse
In addition: There were 23 warnings (use warnings() to see them)
Execution halted

It does work however with other output such as html.

**Comment by jjallaire** [comment]
The problem here is that Radix needs a particular date format. Try this:

```r
date: '`r format(Sys.Date(), "%B %d, %Y")`'
```
