### ISSUE TITLE
gganimate transitions very slowly

### ISSUE THREAD

**Issue by tamannahaque** [rstudio/radix#28]
Hi, I'm using gganimate to create .gifs in Radix, but this seems to be sub-optimal when compared to standard R Markdown- specifically the transitioning between states in the .gif created is much slower and not smooth when outputting in Radix. Is there any fix to make gifs transition optimally in Radix? Thanks :octocat:

**Comment by jjallaire** [comment]
I have no idea what would be causing this. Could you provide an example of the code required to reproduce this?

**Comment by tamannahaque** [comment]
Actually having tested in standard R Markdown again, I think this might be an issue with gganimate instead- will open an issue there instead :)
