### ISSUE TITLE
Sharing links do Not work

### ISSUE THREAD

**Issue by henry090** [rstudio/radix#32]
Hi @jjallaire 
I have 2 questions

1. When I try to share link by clicking on icons, instead of a link it gives me a '404 not found' page. But disqus plugin works fine. **("Note that the base_url field is required in order to use Disqus and sharing links.")** I thought that if Disqus works then sharing links will also work.

2. Is it possible to include in comment section not only disqus but also facebook, twitter and etc.? 
because it seems that latter ones do not work.

**Comment by jjallaire** [comment]
You need to specify a base_url field for sharing links to work. If you have not yet published your blog to the base_url then of course the links won't work. Could that be the problem?

**Comment by henry090** [comment]
Thank you, but I have already published. It still does not work.
About this issue: 
>Is it possible to include in comment section not only disqus but also facebook, twitter and etc.?
because it seems that latter ones do not work.

I don't know why but Safari cannot load facebook, twitter and etc. through disqus plugin. Via Google Chrome it works excellent. So nothing wrong with them.

**Comment by henry090** [comment]
Thank you @jjallaire ! That was my fault. It works, now. I made a mistake in  base_url :)
