### ISSUE TITLE
Figures can not have width smaller than chunk layout

### ISSUE THREAD

**Issue by MarcioFCMartins** [rstudio/radix#41]
When an image is put in a code chunk and a width smaller than the layout width is selected (either through fig.width or out.width), the final image is scaled up to take the full width of the layout. In the case of plots created by code this means the plot is created with the intented size and then scaled up - making fonts larger than intended and making the image pixelated. 

I have tested this with ggplot2::ggplot and knitr::include_graphics and the issue occurs in both - makes it very hard to include small images or plots with large height/width ratios.

**Comment by jjallaire** [comment]
I attempted a fix here: https://github.com/rstudio/radix/commit/d2e4f814aa79f4af9a94f1d356f7dc95614141f4

Let me know if that works as expected for your scenario.

**Comment by MarcioFCMartins** [comment]
Thank you for being so quick. I will do some more tests as I finish my reports but the 2 cases that were giving me issues before are working just fine!  I can now use out.width to change the size of my output or simply leave it blank to display plots at the size rendered by R - just what I wanted.

While I understand why you went with the option of forcing 100%, it's not always the best if the user desires to have plots with certain aspect ratios. In my case, I am using raster files of sediment cores (which are very long but thin) as a background for my plots and to mantain decent aspect ratios I would need gigantic plots.

Thank you for your work into this project, I'm changing most.

**Comment by jjallaire** [comment]
Great, glad it's working as desired now! Let me know if you find other cases that don't quite act the way you want them to.

**Comment by MarcioFCMartins** [comment]
I just encountered another issue - adding a figure caption (via the fig.cap chunk option) sets the out.width to 100% again, even in cases that were fixed by your previous update.

**Comment by jjallaire** [comment]
Thanks for reporting, should be fixed now!
