### ISSUE TITLE
CSS for pre/code blocks

### ISSUE THREAD

**Issue by saptarshiguha** [rstudio/radix#51]
Hello,
Thanks for the nice format. I tried changing the source code aesthetics by including some CSS

```
pre.d-code code.d-code {
  font-family: 'Fira Mono', monospace ;
  font-size: 75%;
}
```

but the code blocks refuse to reflect this. Am I doing something wrong?

**Comment by jjallaire** [comment]
Unfortunately Distill (the framework Radix is based on) uses a shadow dom for styling so there is no way to override CSS for `d-code` :-\

We already do some tweaking of the default Distill styles but we actually have to do it w/ JavaScript b/c of the above limitation:

https://github.com/rstudio/radix/blob/master/inst/rmarkdown/templates/radix_article/resources/distill.html#L691-L699

**Comment by saptarshiguha** [comment]
Thanks! That said, that's a bit unfortunate no? Needing JS to  modify CSS for a report.
Thank you again.
