### ISSUE TITLE
Posts in top-level in _posts are not recognized/rendered

### ISSUE THREAD

**Issue by jemus42** [rstudio/radix#55]
According to the documentation [here](https://rstudio.github.io/radix/blog.html#organizing-posts):

> You can have **all posts at the top level** or you can create subdirectories to create groupings of posts.

This is what I did in my test project here: https://github.com/jemus42/qm.jemu.name
Yet when I run `render_site()`, none of the posts under `_posts` are rendered.  

In a previous iteration, I had all posts in subfolders and everything worked fine, so I'm reasonably certain that the posts themselves are fine.  
I tested on recent CRAN version of radix and current GitHub version.

Am I misinterpreting the documentation?

```
─ Session info ────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       macOS  10.14                
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2018-10-22                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                          
 assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.0)                  
 backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.0)                  
 cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.0)                  
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                  
 digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.0)                  
 evaluate      0.12       2018-10-09 [1] CRAN (R 3.5.0)                  
 fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.0)                  
 glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.0)                  
 htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                  
 httr          1.3.1      2017-08-20 [1] CRAN (R 3.5.0)                  
 jemisc      * 0.0.0.9000 2018-08-24 [1] local                           
 knitr         1.20       2018-02-20 [1] CRAN (R 3.5.0)                  
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.0)                  
 packrat       0.4.9-3    2018-06-01 [1] CRAN (R 3.5.0)                  
 R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.0)                  
 radix       * 0.5.0.9001 2018-10-22 [1] Github (rstudio/radix@d04f173)  
 Rcpp          0.12.19    2018-10-01 [1] CRAN (R 3.5.0)                  
 remotes     * 2.0.1      2018-10-19 [1] CRAN (R 3.5.0)                  
 rmarkdown     1.10       2018-06-11 [1] CRAN (R 3.5.0)                  
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                  
 rsconnect     0.8.8      2018-03-09 [1] CRAN (R 3.5.0)                  
 rstudioapi    0.8        2018-10-02 [1] CRAN (R 3.5.0)                  
 rvest         0.3.2      2016-06-17 [1] CRAN (R 3.5.0)                  
 sessioninfo   1.1.0      2018-09-25 [1] CRAN (R 3.5.0)                  
 stringi       1.2.4      2018-07-20 [1] CRAN (R 3.5.0)                  
 stringr       1.3.1      2018-05-10 [1] CRAN (R 3.5.0)                  
 usethis     * 1.4.0      2018-08-14 [1] CRAN (R 3.5.0)                  
 withr         2.1.2      2018-05-26 [1] Github (jimhester/withr@70d6321)
 xml2          1.2.0      2018-01-24 [1] CRAN (R 3.5.0)                  
 yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.0) 
```

**Comment by jjallaire** [comment]
Each post needs to be in it's own folder (that is what is meant by "top-level", a top-level folder for each post)

**Comment by jemus42** [comment]
That's… not how I interpret that statement, but okay, that's alright.  
I moved each Rmd file in its own folder, but they still don't build.  
Folder structure here: https://github.com/jemus42/qm.jemu.name/tree/master/_posts

I'm starting to suspect there's either a bug or "You can use whatever scheme you like to organize the `_posts` directory" is a slight overstatement :/

**Comment by jjallaire** [comment]
I need more info than "they still don't build". When I try to render your site locally I get this error:

```r
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Calls: <Anonymous> ... withVisible -> eval -> eval -> install.packages -> contrib.url
Execution halted

Exited with status 1.
```

Every other Radix blog uses exactly this structure (`_posts` directory as you have) so my suspicion is that errors you are seeing are not related to folder structure.

**Comment by jemus42** [comment]
Sorry. When I click the RStudio "build" button *or* manually enter `rmarkdown::render_site()` in the console, the site itself is generated correctly, i.e. the index.html and about.html are generated, but none of the posts under `_posts` is generated, i.e. no html files are created.

I have now worked around this by manually rendering each `.Rmd` file under `_posts` and built the site afterwards, now everything shows up properly.  
Since this "concluded" my project and I don't have to touch it again soon, I'm fine with that, but I thought there was either a bug or an issue with the documentation, but if you can't reproduce the problem then I guess you might as well close this issue. 

Regarding your problem building the site, the lack of a set CRAN mirror does not look like a problem with my site because I don't touch CRAN repos anywhere oO

**Comment by jjallaire** [comment]
Okay, now I get what's going on. That's actually the design of Radix -- you render posts individually then they are compiled into a site. If we didn't do it this way then as you got into dozens or hundreds of posts it would take forever to render the site. You also might get into reproducibility issues attempting to render posts from e.g. a couple of years back. So the idea is that you render posts individually as you author them.

**Comment by jemus42** [comment]
Well now I feel silly. Thanks for clearing this up m)

For context: I use blogdown (and love it) and wanted to investigate whether radix could be better for a particular use case. In blogdown, I use `blogdown::build_site()` to rebuild the entire site including all blog posts specifically to catch reproducibility issue in older posts to update them so they are still "valid" today.  

The radix approach, however makes a lot of sense, of course, I just wish there was an easy way to build all the posts. Let's say you're importing a bunch of Rmd files from a different project (as I did) and want to render all of them, then having to render them individually is kind of inconvenient. Maybe a simple helper function that looks for Rmd files under `_posts` and renders them would be neat.

Anyway, my original question in this issue has been cleared up, thanks!
