### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by tamannahaque** [rstudio/radix#59]
Hi, I'm using the latest preview version of RStudio (v1.2.1070-1) but getting errors when creating Radix files- they output correctly but cannot be previewed in the Viewer pane, the below error appears:
```
Output created: Test.html
Error: Radix articles cannot be previewed in this version of RStudio.
Please update to version 1.2.718 or higher at https://www.rstudio.com/products/rstudio/download/preview/
Execution halted
```
Is there a fix for this? (Please let me know if more information is required :octocat:)

**Comment by jjallaire** [comment]
Yes, if you update the Radix package to the latest version from GitHub (`devtools::install_github("rstudio/radix")`) then this error should go away.

**Comment by tamannahaque** [comment]
Thanks for getting back to me, I've tried this and have the following error returned;
```
devtools::install_github("rstudio/radix")
Downloading GitHub repo rstudio/radix@master
from URL https://api.github.com/repos/rstudio/radix/zipball/master
Installation failed: Failure when receiving data from the peer

```
I'm not sure if this is an issue with Radix, but I can update other packages from GitHub successfully.

**Comment by jjallaire** [comment]
That must be an intermittent error (I can't reproduce it). I would just try again.

**Comment by tamannahaque** [comment]
It's happening to me persistently, but seems like just me. Thanks for your help :octocat:
