### ISSUE TITLE
Radix blog 'not mobile friendly' - option to soft wrap code chunks on mobile?

### ISSUE THREAD

**Issue by ulyngs** [rstudio/radix#62]
Google tells me my recently built Radix blog ([ulyngs.github.io/blog](https://ulyngs.github.io/blog/) is "not mobile friendly", because it's got "content wider than the screen".

<img width="1440" alt="screenshot 2018-11-11 at 09 22 55" src="https://user-images.githubusercontent.com/23137032/48311180-c4d44900-e593-11e8-9d37-023d2e73d06b.png">

Scrolling through the site on a mobile device, the only instance I can find of this is in code chunks.
<img width="1440" alt="screenshot 2018-11-11 at 09 21 46" src="https://user-images.githubusercontent.com/23137032/48311218-52b03400-e594-11e8-9e03-1fe86718fd10.png">

Is it possible to add an option to soft wrap content in code chunks on mobile devices? (This might require including line numbers so that it is clear what is a text wrapping and what is a line break)

**Comment by ulyngs** [comment]
I fixed this on my site by adding this CSS:

```css
d-code {
  overflow-x: auto;
}
```

**Comment by jjallaire** [comment]
Thanks for reporting this as well as for the fix! Should be addressed by this commit: https://github.com/rstudio/radix/commit/abbfd67146e44eb873c561cbb1fc11065788f7f8

Could you rebuild your site w/o the local workaround to ensure that my fix has the intended effect on Google's assessment of mobile friendliness?
