### ISSUE TITLE
Package ahead of available preview release.

### ISSUE THREAD

**Issue by smmurphy** [rstudio/radix#69]
Thanks for your work on this package, which I am very excited to use for various projects. So excited in fact that I am wondering when it will be in sync with a version of R Studio that can run it. So along those lines I have 2 questions...

1) Is there an ETA for a release of RStudio that will align with the package currently on CRAN?
2) If that release is still some ways in the future is a stable release of this package possible that would at least align with the current preview version of RStudio?

```
Error: Radix articles cannot be previewed in this version of RStudio.
Please update to version 1.2.718 or higher at https://www.rstudio.com/products/rstudio/download/preview/

Current available version of preview release is v1.2.1181-3.
```

**Comment by jjallaire** [comment]
The CRAN release has now been updated  (we were waiting on bookdown going to CRAN which happened last week).
