### ISSUE TITLE
radix not rendering b/c upstream asset server cannot be reached (invalid https cert)

### ISSUE THREAD

**Issue by maxheld83** [rstudio/radix#71]
Radix output (`index.html`) currently appear to render invisibly on Safari (Desktop 12.0.2., Mobile iOS 12.1.1).
All I get is a blank, but scrollable screen.

This affects https://rstudio.github.io/radix/ as well as any radix project viewed inside the RStudio viewer (on macOS, which uses Safari to render under the hood, AFAIK), including the simple boilerplate template for radix.

My hunch is that this the following CSS never gets disabled on render, as it probably should:

```
<style type="text/css">
  /* Hide doc at startup (prevent jankiness while JS renders/transforms) */
  body {
    visibility: hidden;
  }
  </style>
```

Manually deleting this section from the `index.html` lets Safari show the website, though the css (fonts) are mucked up.

So I am guessing the following JS never gets executed on Safari:

```
on_load_complete();
```

**Comment by maxheld83** [comment]
nevermind, this appears to be an issue with upstream distill.pub assets – their https certificate (or something) is invalid:

<img width="2044" alt="distill" src="https://user-images.githubusercontent.com/5372770/50092233-d00f3a00-020d-11e9-8f1d-675db32dad0d.png">

distill.pub is currently unreachable from both Safari and Chrome, so my guess would be that radix websites continued to work in Chrome because of some asset caching.

Still kinda sucks.

I'll raise the alarm upstream.

**Comment by maxheld83** [comment]
so I this could technically be closed, but perhaps it can remain open until the upstream problem is solved, in case other people run into this.

**Comment by henry090** [comment]
> on Safari (Desktop 12.0.2., Mobile iOS 12.1.1).

Yes, it works **only** on Google Chrome (Desktop)...

**Comment by maxheld83** [comment]
Solved.
