### ISSUE TITLE
Issue deploying on netlify

### ISSUE THREAD

**Issue by shamindras** [rstudio/radix#74]
Hi All,

I have decided to change from my [blogdown blog](https://github.com/shamindras/ss_personal_blog) to a [radix blog](https://github.com/shamindras/ss_radix_personal_blog).

I followed the setup of the `radix` [blog instructions](https://rstudio.github.io/radix/blog.html) in detail and have the master branch with default [blog content ready to deploy](https://github.com/shamindras/ss_radix_personal_blog).

I want to deploy this on `netlify` using my [original url](www.shamindras.com). I changed the repository to be my new radix one. I left the `Base directory:` and `Build command:` and `Publish directory:` as `Not Set` in `netlify` as I the `radix` package did not create a `_site` directory.

My site is not deployed correctly. Note that`netlify` does not have any deploy errors but I keep seeing 

> Page Not found Looks like you've followed a broken link or entered a URL that doesn't exist on this site.". 

Could anyone please let me know the `netlify` settings to use? I feel I'm close now :)

Thanks

**Comment by jjallaire** [comment]
Here are the instructions for Netlify: https://rstudio.github.io/radix/publish_website.html#netlify

Radix will create a _site directory by default unless you override that in your site config. 

One thing to consider is that you need to actually check your `_site` directory into version control if Netlify is syncing your site from e.g. GitHub.

**Comment by shamindras** [comment]
Thanks @jjallaire. So I folllowed those instructions but since I created a `radix blog` there was no `_site` folder.

I realized that for radix blogs that the default `output_dir` is `docs`. Once I set the netlify publish directory to `docs` it all worked out.

Did I do the right thing in your opinion? If so, would you like me to create a PR to specify this blog specific `netlify` requirement to make it easier for other new users?

**Comment by jjallaire** [comment]
No, the default is `_site` (however if you configure your blog for GitHub Pages, which is one of the available options when creating, then it will indeed be `docs`.

**Comment by shamindras** [comment]
Thanks! I did configure for GitHub Pages - so this makes sense.
