### ISSUE TITLE
Feature/docs inquiry: Academicons?

### ISSUE THREAD

**Issue by mbjoseph** [rstudio/radix#76]
The font-awesome icons are great, but as an academic using radix, i would love to be able to include icons for services like Figshare, the *xiv preprint servers, Dryad, Google Scholar, ORCID, etc., which are all supported by Academicons: https://jpswalsh.github.io/academicons/

Any interest in supporting Academicons by default, or adding information to the docs for how to install/use them?

**Comment by jjallaire** [comment]
This isn't a built-in feature, but you can certainly add Academicons to a Radix document by doing the following:

1. Set `self_contained: false` in the output options:

    ```yaml
    output: 
      radix::radix_article:
        self_contained: false
    ```

2. Include the stylesheet link as well as any icons you want using HTML, e.g.

    ```html
    <link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">

    <i class="ai ai-google-scholar-square ai-3x"></i>
    ```

**Comment by mbjoseph** [comment]
Great - thanks @jjallaire!
